name: meow_dart
description: A portable YouTube archiver.
version: 1.0.0
repository: https://github.com/tytydraco/meow_dart
publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.1
  io: ^1.0.3
  path: ^1.8.2
  pool: ^1.5.1
  stdlog:
    git: https://github.com/tytydraco/stdlog
  youtube_explode_dart: ^2.3.9

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: any

executables:
  meow_dart:
